---
on:
  push:
    tags:
      - "*"
name: Build
env:
  BSP: 32.7.4
  UBUNTU: 22.04
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y podman qemu-user-static lrzip
          sudo systemctl start systemd-binfmt.service

      - name: Create rootfs
        run: just build-jetson-rootfs

      - name: Build jetson image for Jetson nano revision 300
        run: |
          just build-jetson-image  \
            jetson-nano \
            300
          mv jetson.img "jetson-nano-300_${UBUNTU}_${BSP}.img"
          lrzip "jetson-nano-300_${UBUNTU}_${BSP}.img"
          rm -rf "jetson-nano-300_${UBUNTU}_${BSP}.img"
          ls -lht "jetson-nano-300_${UBUNTU}_${BSP}.img.lrz"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            [CHANGELOG.md](${{ github.server_url }}/${{ github.repository }}/blob/master/CHANGELOG.md)
          files: "jetson*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
